### ISSUE TITLE
getGeohashesBetweenTwoGeohashes() incorrect results

### ISSUE THREAD

**Issue by mailinger-mate** [alrico88/geohashes-between#1]
Hello @alrico88,

It seems the `getGeohashesBetweenTwoGeohashes(start, end)` method is not getting the correct number of geohashes and sometimes not even ones in between start and end:
https://codesandbox.io/s/geohashes-between-9282je

Just letting you know.

Regards,
Mate

**Comment by alrico88** [comment]
Hello @mailinger-mate 

Could you provide a reproduction of it not working as intended? The provided code works as it should. Bear in mind that if you don't provide de third parameter (includeStartEnd to true) it will not include start and end.

![input](https://user-images.githubusercontent.com/6015036/209541880-9439be19-7430-49c8-ba32-746294c60a94.png)
![map](https://user-images.githubusercontent.com/6015036/209541890-e9421f09-eff9-47aa-8caf-407914b0ed15.png)
